### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by khanzainub** [riffomonas/Schloss_rrnAnalysis_XXXX_2020#1]
Hello sir! the data you shared link youn you is unavaible here. I need it for practice.

**Comment by pschloss** [comment]
Hi - you can get the complete and final repository at https://github.com/SchlossLab/Schloss_rrnAnalysis_mSphere_2021.

To generate the files, you'l need to do...

`make submission/manuscript.pdf`

Of course, you'll also need to have all of the tools installed including GNU Make.
